tinymce:
    plugins: "advlist autolink link image media table lists code"
    toolbar: "bold italic underline | alignleft aligncenter alignright alignjustify | bullist numlist | link image media | table | code"
