sonar.projectKey=kXsato_CesiZen
sonar.organization=kxsato

sonar.sources=src
sonar.tests=tests

sonar.exclusions=var/**,vendor/**,public/**,assets/vendor/**

sonar.php.coverage.reportPaths=coverage.xml
sonar.php.tests.reportPath=junit.xml

sonar.coverage.exclusions=\
  src/DataFixtures/**,\
  src/Kernel.php
